import AltilloCore
import AppKit
import Foundation
import Testing
@testable import Altillo

/// Phase 12's clipboard and Shortcuts sections: what the clipboard never keeps, how its history behaves and is
/// saved, how `shortcuts` output is read and runs are built, and how Ask reaches both. Nothing here touches the
/// user's pasteboard, defaults or shortcuts: private pasteboards, private defaults, scratch files and fake runners.
@MainActor
struct ClipboardShortcutsTests {
    private let now = Date(timeIntervalSinceReferenceDate: 800_000_000)

    private static func makeDefaults(_ name: String = #function) -> UserDefaults {
        TestDefaultsJanitor.purgeStale()
        let suite = "me.badia.altillo.tests.clipshort.\(name.replacingOccurrences(of: "()", with: ""))-\(UUID().uuidString)"
        UserDefaults.standard.removePersistentDomain(forName: suite)
        return UserDefaults(suiteName: suite)!
    }

    private static func scratchArchive() -> ClipboardArchive {
        ClipboardArchive(url: FileManager.default.temporaryDirectory
            .appendingPathComponent("altillo-clipboard-tests-\(UUID().uuidString)/history.json"))
    }

    /// A store on a pasteboard of its own, with the frontmost app decided by the test.
    private static func makeStore(
        frontmost: String? = "com.apple.TextEdit",
        defaults: UserDefaults = makeDefaults(),
        archive: ClipboardArchive = scratchArchive()
    ) -> (ClipboardStore, NSPasteboard) {
        let pasteboard = NSPasteboard.withUniqueName()
        let store = ClipboardStore(pasteboard: pasteboard, defaults: defaults, archive: archive,
                                   frontmostBundleID: { frontmost })
        return (store, pasteboard)
    }

    private static func put(_ text: String, on pasteboard: NSPasteboard, marking extra: [String] = [],
                            source: String? = nil) {
        var types: [NSPasteboard.PasteboardType] = [.string] + extra.map { .init($0) }
        if source != nil { types.append(.init(ClipboardPrivacy.sourceType)) }
        pasteboard.declareTypes(types, owner: nil)
        pasteboard.setString(text, forType: .string)
        for type in extra { pasteboard.setString("", forType: .init(type)) }
        if let source { pasteboard.setString(source, forType: .init(ClipboardPrivacy.sourceType)) }
    }

    // MARK: - What is never kept

    @Test func markedPrivateCopiesAreNeverRead() {
        for marker in [ClipboardPrivacy.concealedType, ClipboardPrivacy.transientType,
                       ClipboardPrivacy.autoGeneratedType, "com.agilebits.onepassword",
                       "de.petermaurer.TransientPasteboardType"] {
            #expect(ClipboardPrivacy.decide(types: ["public.utf8-plain-text", marker], frontmostBundleID: nil)
                == .skipPrivate, "\(marker)")
        }
        #expect(ClipboardPrivacy.decide(types: ["public.utf8-plain-text"], frontmostBundleID: "com.apple.Safari") == .record)
        #expect(ClipboardPrivacy.decide(types: ["public.url"], frontmostBundleID: nil) == .record)
        #expect(ClipboardPrivacy.decide(types: ["public.file-url", "public.utf8-plain-text"], frontmostBundleID: nil) == .skipNotText)
        #expect(ClipboardPrivacy.decide(types: ["public.png", "public.tiff"], frontmostBundleID: nil) == .skipNotText)
        #expect(ClipboardPrivacy.decide(types: [], frontmostBundleID: nil) == .skipNotText)
    }

    @Test func passwordManagersAreRecognisedByBundleID() {
        for id in ["com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword8-beta",
                   "com.apple.Passwords", "com.apple.keychainaccess", "com.bitwarden.desktop",
                   "org.keepassxc.keepassxc", "com.lastpass.LastPass", "me.proton.pass.electron"] {
            #expect(ClipboardPrivacy.isPasswordManager(id), "\(id)")
        }
        for id in ["com.apple.Safari", "com.apple.Notes", "com.microsoft.VSCode", ""] {
            #expect(!ClipboardPrivacy.isPasswordManager(id), "\(id)")
        }
        #expect(!ClipboardPrivacy.isPasswordManager(nil))
        #expect(ClipboardPrivacy.decide(types: ["public.utf8-plain-text"], frontmostBundleID: "com.1password.1password")
            == .skipPrivate, "an unmarked copy in a password manager is still private")
    }

    @Test func emptyAndHugeTextsAreNotKept() {
        #expect(ClipboardPrivacy.keepable(nil) == nil)
        #expect(ClipboardPrivacy.keepable("  \n\t ") == nil)
        #expect(ClipboardPrivacy.keepable(String(repeating: "x", count: ClipboardPrivacy.maxTextLength + 1)) == nil)
        #expect(ClipboardPrivacy.keepable(" hola ") == " hola ", "kept exactly as copied")
    }

    @Test func theStoreSkipsConcealedTransientAndPasswordManagerCopies() {
        let (store, pasteboard) = Self.makeStore()
        defer { pasteboard.releaseGlobally() }

        Self.put("hunter2", on: pasteboard, marking: [ClipboardPrivacy.concealedType])
        store.check()
        Self.put("restored soon", on: pasteboard, marking: [ClipboardPrivacy.transientType])
        store.check()
        Self.put("from a helper", on: pasteboard, source: "com.bitwarden.desktop")
        store.check()
        #expect(store.history.isEmpty)

        Self.put("Buy milk", on: pasteboard)
        store.check()
        #expect(store.history.items.map(\.text) == ["Buy milk"])
        #expect(store.history.items.first?.sourceBundleID == "com.apple.TextEdit")

        // Nothing new: the same change count is only looked at once.
        store.check()
        #expect(store.history.items.count == 1)
    }

    @Test func nothingIsKeptWhileAPasswordManagerIsInFront() {
        let (store, pasteboard) = Self.makeStore(frontmost: "com.apple.Passwords")
        defer { pasteboard.releaseGlobally() }
        Self.put("correct horse battery staple", on: pasteboard)
        store.check()
        #expect(store.history.isEmpty)
    }

    @Test func copyingBackPutsTheTextOnTheClipboardWithoutADuplicate() {
        let (store, pasteboard) = Self.makeStore()
        defer { pasteboard.releaseGlobally() }
        Self.put("first", on: pasteboard); store.check()
        Self.put("second", on: pasteboard); store.check()
        let first = try! #require(store.history.items.last)

        store.copy(first)
        #expect(pasteboard.string(forType: .string) == "first")
        #expect(store.justCopied == first.id)
        store.check()
        #expect(store.history.items.map(\.text) == ["first", "second"], "moved to the top, not added twice")
    }

    // MARK: - The history

    @Test func copyingTheSameTextAgainMovesItToTheTop() {
        var history = ClipboardHistory()
        let a = history.record("a", at: now)
        history.record("b", at: now.addingTimeInterval(1))
        history.togglePin(a.id)
        history.record("a", at: now.addingTimeInterval(2), sourceBundleID: "com.apple.Safari")
        #expect(history.items.map(\.text) == ["a", "b"])
        #expect(history.items.first?.id == a.id, "the same slip, not a new one")
        #expect(history.items.first?.isPinned == true, "keeps its pin")
        #expect(history.items.first?.copiedAt == now.addingTimeInterval(2))
        #expect(history.items.first?.sourceBundleID == "com.apple.Safari")
    }

    @Test func theHistoryKeepsFiftyAndNeverDropsPins() {
        var history = ClipboardHistory()
        let oldest = history.record("oldest", at: now)
        history.togglePin(oldest.id)
        for index in 0..<80 {
            history.record("copy \(index)", at: now.addingTimeInterval(Double(index + 1)))
        }
        #expect(history.items.count == ClipboardHistory.maxItems)
        #expect(history.items.contains { $0.id == oldest.id }, "pinned slips aren't pushed out")
        #expect(history.recent.first?.text == "copy 79")
        #expect(!history.items.contains { $0.text == "copy 0" }, "the oldest unpinned went first")
        #expect(history.ordered.first?.id == oldest.id, "pins come first")
    }

    @Test func pinsAreCapped() {
        var history = ClipboardHistory()
        var items: [ClipboardItem] = []
        for index in 0...ClipboardHistory.maxPinned { items.append(history.record("t\(index)", at: now)) }
        for item in items.dropLast() {
            let pinned = history.togglePin(item.id)
            #expect(pinned)
        }
        #expect(!history.canPinMore)
        let extra = history.togglePin(items.last!.id)
        #expect(!extra)
        #expect(history.pinned.count == ClipboardHistory.maxPinned)
        let unpinned = history.togglePin(items[0].id)
        #expect(unpinned, "unpinning always works")
    }

    @Test func clearingKeepsPinsAndCanBeUndone() {
        let (store, pasteboard) = Self.makeStore()
        defer { pasteboard.releaseGlobally() }
        for text in ["one", "two", "three"] {
            Self.put(text, on: pasteboard)
            store.check()
        }
        let pinned = store.history.items.first { $0.text == "two" }!
        store.togglePin(pinned)

        store.clear()
        #expect(store.history.items.map(\.text) == ["two"])
        #expect(store.undoable?.kind == .clear)
        store.undo()
        #expect(store.history.items.count == 3)
        #expect(store.undoable == nil)

        let doomed = store.history.items.first { $0.text == "three" }!
        store.delete(doomed)
        #expect(!store.history.items.contains { $0.id == doomed.id })
        store.undo()
        #expect(store.history.items.contains { $0.id == doomed.id })
    }

    @Test func searchIgnoresCaseAndAccents() {
        var history = ClipboardHistory()
        history.record("Reunión con Marta a las 10", at: now)
        history.record("Tracking number 1Z999", at: now)
        #expect(history.matching("reunion marta").map(\.text) == ["Reunión con Marta a las 10"])
        #expect(history.matching("TRACKING").count == 1)
        #expect(history.matching("").count == 2)
        #expect(history.matching("nada").isEmpty)
    }

    @Test func arrowsWalkTheSlipsAndReturnCopies() {
        let (store, pasteboard) = Self.makeStore()
        defer { pasteboard.releaseGlobally() }
        for text in ["one", "two", "three"] {
            Self.put(text, on: pasteboard)
            store.check()
        }
        store.moveSelection(1)
        #expect(store.selection == store.visibleItems[0].id)
        store.moveSelection(1)
        store.moveSelection(1)
        store.moveSelection(1)
        #expect(store.selection == store.visibleItems[2].id, "stops at the last slip")
        let copied = store.copySelection()
        #expect(copied?.text == "one")
        #expect(pasteboard.string(forType: .string) == "one")
    }

    @Test func theSlipShowsTwoLines() {
        let item = ClipboardItem(text: "\n  First line  \n\nSecond\nThird", copiedAt: now)
        #expect(item.preview == "First line\nSecond")
        #expect(item.title == "First line")
    }

    // MARK: - Keeping it across launches

    @Test func historyStaysInMemoryUnlessTheUserAsksToKeepIt() throws {
        let defaults = Self.makeDefaults()
        let archive = Self.scratchArchive()
        defer { try? FileManager.default.removeItem(at: archive.url.deletingLastPathComponent()) }

        let (store, pasteboard) = Self.makeStore(defaults: defaults, archive: archive)
        defer { pasteboard.releaseGlobally() }
        #expect(!store.keepsHistory, "off by default")
        Self.put("secret-ish note", on: pasteboard)
        store.check()
        store.stop()
        #expect(!FileManager.default.fileExists(atPath: archive.url.path), "nothing on disk while it's off")

        store.keepsHistory = true
        #expect(defaults.bool(forKey: ClipboardStore.keepsHistoryKey))
        #expect(FileManager.default.fileExists(atPath: archive.url.path))
        let permissions = try FileManager.default.attributesOfItem(atPath: archive.url.path)[.posixPermissions] as? Int
        #expect(permissions == 0o600)
        #expect(archive.load()?.items.map(\.text) == ["secret-ish note"])

        // A new launch with the option on finds it again.
        let (relaunched, other) = Self.makeStore(defaults: defaults, archive: archive)
        defer { other.releaseGlobally() }
        #expect(relaunched.keepsHistory)
        relaunched.start()
        #expect(relaunched.history.items.map(\.text) == ["secret-ish note"])
        relaunched.keepsHistory = false
        #expect(!FileManager.default.fileExists(atPath: archive.url.path), "turning it off deletes the file")
        relaunched.stop()
        #expect(relaunched.history.isEmpty, "turning the section off forgets what's in memory")
    }

    @Test func theWatcherFollowsTheSection() async throws {
        let settings = AltilloSettings(defaults: Self.makeDefaults())
        let (store, pasteboard) = Self.makeStore()
        defer { pasteboard.releaseGlobally() }
        settings.setEnabled(.clipboard, false)
        store.follow(settings)
        #expect(!store.isWatching, "opt-in: nothing is watched while the section is off")

        settings.setEnabled(.clipboard, true)
        for _ in 0..<100 where !store.isWatching { try await Task.sleep(for: .milliseconds(10)) }
        #expect(store.isWatching)

        settings.setEnabled(.clipboard, false)
        for _ in 0..<100 where store.isWatching { try await Task.sleep(for: .milliseconds(10)) }
        #expect(!store.isWatching, "turning the section off stops the timer")
    }

    // MARK: - Shortcuts: reading the list

    @Test func parsesNamesWithSpacesEmojiAndParentheses() {
        let output = """
        Aurio · Apple Pay (50711DFB-2D7D-4AD4-927F-FFF49E45E07C)
        ☕️ Coffee time (C1AFA98C-8F25-4078-8E29-44598581E256)
        Resize (big) images (565aa99e-4707-427a-9f8f-fed9e7aef419)
          Say "hi" to Ana   (F007AD75-1811-4EBF-B989-B72960F2FF27)

        No identifier here (not-a-uuid)
        """
        let shortcuts = ShortcutsCLI.parseList(output, folder: "Starter")
        #expect(shortcuts.map(\.name) == ["Aurio · Apple Pay", "☕️ Coffee time", "Resize (big) images", "Say \"hi\" to Ana",
                                          "No identifier here (not-a-uuid)"])
        #expect(shortcuts[0].identifier == "50711DFB-2D7D-4AD4-927F-FFF49E45E07C")
        #expect(shortcuts[2].identifier == "565aa99e-4707-427a-9f8f-fed9e7aef419")
        #expect(shortcuts[4].identifier == nil)
        #expect(shortcuts[4].id == "No identifier here (not-a-uuid)", "a name is the id when there's no identifier")
        #expect(shortcuts.allSatisfy { $0.folder == "Starter" })
        #expect(ShortcutsCLI.parseList("").isEmpty)
    }

    @Test func listArgumentsAskForIdentifiers() {
        #expect(ShortcutsCLI.listArguments() == ["list", "--show-identifiers"])
        #expect(ShortcutsCLI.listArguments(folders: true) == ["list", "--show-identifiers", "--folders"])
        #expect(ShortcutsCLI.listArguments(folder: "Work stuff") == ["list", "--show-identifiers", "--folder-name", "Work stuff"])
    }

    // MARK: - Shortcuts: running

    @Test func runsByIdentifierAndNeverLetsANameBecomeAnOption() {
        let byID = ShortcutInfo(name: "Coffee", identifier: "C1AFA98C-8F25-4078-8E29-44598581E256")
        #expect(ShortcutsCLI.runArguments(for: byID) == ["run", "--", "C1AFA98C-8F25-4078-8E29-44598581E256"])

        let sneaky = ShortcutInfo(name: "--output-path", identifier: nil)
        #expect(ShortcutsCLI.runArguments(for: sneaky) == ["run", "--", "--output-path"])

        let quoted = ShortcutInfo(name: "Say \"hi\" & it's 🎉", identifier: nil)
        let input = URL(fileURLWithPath: "/tmp/My input.txt")
        let arguments = ShortcutsCLI.runArguments(for: quoted, inputPath: input)
        #expect(arguments == ["run", "--input-path", "/tmp/My input.txt", "--", "Say \"hi\" & it's 🎉"],
                "passed verbatim: there's no shell to escape for")
        #expect(ShortcutsCLI.displayCommand(arguments)
            == "/usr/bin/shortcuts run --input-path '/tmp/My input.txt' -- 'Say \"hi\" & it'\\''s 🎉'")
        #expect(ShortcutsCLI.shellQuoted("plain-name") == "plain-name")
        #expect(ShortcutsCLI.shellQuoted("") == "''")
    }

    @Test func failuresReadLikeSentences() {
        let output = ShortcutsCLI.Output(status: 1, standardOutput: "",
                                         standardError: "Error: The operation couldn’t be completed. Couldn’t find shortcut\n")
        #expect(ShortcutsCLI.failureMessage(output) == "Couldn’t find shortcut")
        #expect(ShortcutsCLI.failureMessage(.init(status: 3, standardOutput: "", standardError: "")).contains("3"))
    }

    @Test func matchesWhatSomeoneTyped() {
        let shortcuts = [
            ShortcutInfo(name: "☕️ Coffee Time", identifier: "1"),
            ShortcutInfo(name: "Backup Photos", identifier: "2"),
            ShortcutInfo(name: "Backup Code", identifier: "3"),
            ShortcutInfo(name: "Café con leche", identifier: "4"),
        ]
        #expect(ShortcutsCLI.match("coffee time", in: shortcuts) == .found(shortcuts[0]))
        #expect(ShortcutsCLI.match("Coffee", in: shortcuts) == .found(shortcuts[0]), "the only one with that word")
        #expect(ShortcutsCLI.match("cafe con leche", in: shortcuts) == .found(shortcuts[3]))
        #expect(ShortcutsCLI.match("backup", in: shortcuts) == .ambiguous([shortcuts[1], shortcuts[2]]))
        #expect(ShortcutsCLI.match("Deploy", in: shortcuts) == .none)
        #expect(ShortcutsCLI.match("  ", in: shortcuts) == .none)
        #expect(ShortcutsCLI.match("co", in: shortcuts) == .none, "too short to guess from")
    }

    /// Everything a fake `shortcuts` was asked to do.
    private actor Calls {
        private(set) var arguments: [[String]] = []
        private(set) var inputs: [String] = []
        func add(_ call: [String]) {
            arguments.append(call)
            if let index = call.firstIndex(of: "--input-path"), call.indices.contains(index + 1),
               let text = try? String(contentsOfFile: call[index + 1], encoding: .utf8) {
                inputs.append(text)
            }
        }
    }

    private static func makeShortcuts(
        _ list: [ShortcutInfo],
        calls: Calls,
        defaults: UserDefaults = makeDefaults(),
        result: ShortcutsCLI.Output = .init(status: 0, standardOutput: "Done!\n", standardError: "")
    ) -> ShortcutsStore {
        ShortcutsStore(
            defaults: defaults,
            lister: { list },
            runner: { arguments in
                await calls.add(arguments)
                return result
            }
        )
    }

    @Test func runningReportsSuccessFailureAndCleansTheInputUp() async throws {
        let calls = Calls()
        let coffee = ShortcutInfo(name: "Coffee", identifier: "AAAAAAAA-0000-0000-0000-000000000001")
        let store = Self.makeShortcuts([coffee], calls: calls)
        await store.loadIfNeeded()
        #expect(store.phase == .ready)

        let state = await store.run(coffee, input: .text("Hola, Ana", label: "the clipboard’s text"))
        #expect(state == .succeeded(output: "Done!"))
        #expect(store.runs[coffee.id] == .succeeded(output: "Done!"))
        #expect(store.lastOutcome?.shortcut == coffee)
        let arguments = await calls.arguments
        #expect(arguments.count == 1)
        #expect(arguments[0].first == "run" && arguments[0].last == coffee.identifier)
        #expect(await calls.inputs == ["Hola, Ana"], "the text reached the shortcut as a file")
        let path = try #require(arguments[0].firstIndex(of: "--input-path").map { arguments[0][$0 + 1] })
        #expect(!FileManager.default.fileExists(atPath: path), "the input file is gone afterwards")

        let failing = Self.makeShortcuts([coffee], calls: Calls(),
                                         result: .init(status: 1, standardOutput: "", standardError: "Error: Nope"))
        #expect(await failing.run(coffee) == .failed("Nope"))
    }

    @Test func pinsAreRememberedInTheirOrder() async {
        let defaults = Self.makeDefaults()
        let list = ["One", "Two", "Three"].enumerated().map { ShortcutInfo(name: $1, identifier: "id-\($0)") }
        let store = Self.makeShortcuts(list, calls: Calls(), defaults: defaults)
        await store.loadIfNeeded()
        store.togglePin(list[2])
        store.togglePin(list[0])
        #expect(store.pinned.map(\.name) == ["Three", "One"])
        #expect(store.listed.map(\.name) == ["Two"], "the list holds the rest")
        store.query = "o"
        #expect(Set(store.listed.map(\.name)) == ["One", "Two"], "a search covers pins too")

        let again = Self.makeShortcuts(list, calls: Calls(), defaults: defaults)
        await again.loadIfNeeded()
        #expect(again.pinned.map(\.name) == ["Three", "One"])
        again.togglePin(list[2])
        #expect(again.pinned.map(\.name) == ["One"])
    }

    @Test func aMissingCommandIsSaidPlainly() async {
        let store = ShortcutsStore(defaults: Self.makeDefaults(), lister: { throw ShortcutsCLI.Failure.missing },
                                   runner: { _ in throw ShortcutsCLI.Failure.missing })
        await store.loadIfNeeded()
        #expect(store.phase == .missing)
        let state = await store.run(ShortcutInfo(name: "X", identifier: nil))
        guard case .failed = state else {
            Issue.record("expected a failure, got \(state)")
            return
        }
    }

    // MARK: - Ask

    @Test func onlyAnExplicitRequestRunsAShortcut() {
        for question in ["Run my Coffee shortcut", "run the shortcut Backup Photos", "Can you run my ☕️ shortcut?",
                         "Ejecuta el atajo Café", "lanza mi atajo de copia", "Executa la drecera Cafè, si us plau",
                         "run my clipboard shortcut"] {
            #expect(AssistantRouter.route(question, now: now) == .shortcut, "\(question)")
        }
        for question in ["How do I run a shortcut?", "¿Cómo ejecuto un atajo?", "What is a shortcut?",
                         "What's the keyboard shortcut for copy?", "run a shortcut", "Set a timer for 10 minutes",
                         "What did I copy earlier?"] {
            #expect(AssistantRouter.route(question, now: now) != .shortcut, "\(question)")
        }
        #expect(AssistantRouter.route("What did I copy earlier?", now: now) == .context)
    }

    @Test func eachRouteGetsOnlyItsTools() {
        let shortcut = AssistantTools.all(for: .shortcut, shelfItems: { [] }, report: { _ in }).map(\.name)
        #expect(shortcut == ["runShortcut"])
        let context = AssistantTools.all(for: .context, shelfItems: { [] }, report: { _ in }).map(\.name)
        #expect(context.contains("clipboardHistory"))
        #expect(!context.contains("runShortcut"), "reading questions never get the action")
        #expect(AssistantTools.all(for: .chat, shelfItems: { [] }, report: { _ in }).isEmpty)
        let instructions = AssistantInstructions.text(route: .shortcut)
        #expect(instructions.contains("runShortcut"))
        #expect(instructions.count < 900)
    }

    @Test func clipboardHistoryToolSaysWhatItKnows() {
        let off = ClipboardAsk.answer(.init(isEnabled: false, items: []), search: nil, now: now)
        #expect(off.contains("off"))
        let empty = ClipboardAsk.answer(.init(isEnabled: true, items: []), search: nil, now: now)
        #expect(empty.contains("Nothing copied"))

        let items = [
            ClipboardItem(text: "Tracking 1Z999", copiedAt: now.addingTimeInterval(-7_200), sourceName: "Mail", isPinned: true),
            ClipboardItem(text: "Meet at 6\nby the window", copiedAt: now.addingTimeInterval(-60), sourceName: "Messages"),
        ]
        let answer = ClipboardAsk.answer(.init(isEnabled: true, items: items), search: nil, now: now)
        let meet = try! #require(answer.range(of: "Meet at 6 by the window"))
        let tracking = try! #require(answer.range(of: "Tracking 1Z999"))
        #expect(meet.lowerBound < tracking.lowerBound, "newest first")
        #expect(answer.contains("from Mail (pinned)"))
        #expect(answer.contains("1 min ago"))

        let found = ClipboardAsk.answer(.init(isEnabled: true, items: items), search: "tracking", now: now)
        #expect(found.contains("Tracking 1Z999") && !found.contains("Meet"))
        let missing = ClipboardAsk.answer(.init(isEnabled: true, items: items), search: "invoice", now: now)
        #expect(missing.contains("None of the 2"))
    }

    @Test func askRunsANamedShortcutOnceAndSaysHowItWent() async {
        let calls = Calls()
        let id = "BBBBBBBB-0000-0000-0000-\(String(UUID().uuidString.suffix(12)))"
        let coffee = ShortcutInfo(name: "☕️ Coffee Time", identifier: id)
        let backups = [ShortcutInfo(name: "Backup Photos", identifier: "p-\(id)"),
                       ShortcutInfo(name: "Backup Code", identifier: "c-\(id)")]
        let store = Self.makeShortcuts([coffee] + backups, calls: calls)

        let off = await ShortcutsAsk.run("coffee time", store: store, isEnabled: false, now: now)
        #expect(off.contains("Nothing was run"))
        let unknown = await ShortcutsAsk.run("Deploy", store: store, isEnabled: true, now: now)
        #expect(unknown.contains("no shortcut called") && unknown.contains("Nothing was run"))
        let ambiguous = await ShortcutsAsk.run("backup", store: store, isEnabled: true, now: now)
        #expect(ambiguous.contains("More than one") && ambiguous.contains("Nothing was run"))
        #expect(await calls.arguments.isEmpty, "nothing ran for any of those")

        let ran = await ShortcutsAsk.run("coffee time", store: store, isEnabled: true, now: now)
        #expect(ran.contains("Ran the shortcut \"☕️ Coffee Time\""))
        #expect(ran.contains("Done!"))
        let again = await ShortcutsAsk.run("Coffee Time", store: store, isEnabled: true, now: now.addingTimeInterval(3))
        #expect(again.contains("wasn't run again"), "a retried answer never runs it twice")
        #expect(await calls.arguments.count == 1)
    }

    @Test func askSaysWhenAShortcutIsStillRunning() {
        let shortcut = ShortcutInfo(name: "Long one", identifier: nil)
        #expect(ShortcutsAsk.sentence(for: shortcut, state: nil).contains("still running"))
        #expect(ShortcutsAsk.sentence(for: shortcut, state: .failed("Nope")).contains("failed: Nope"))
    }
}
