import Foundation

// The clipboard section's plain logic, none of it touching the pasteboard: what may be kept, the history itself
// (dedupe, pins, the cap) and where it's saved when the user wants it to survive a relaunch.

/// One thing the user copied: text only.
struct ClipboardItem: Identifiable, Codable, Hashable, Sendable {
    var id: UUID
    var text: String
    /// When it was last copied (copying the same text again brings it back to the top).
    var copiedAt: Date
    /// The app it came from: `org.nspasteboard.source` when the app says so, else the frontmost app.
    var sourceBundleID: String?
    var sourceName: String?
    var isPinned: Bool

    init(id: UUID = UUID(), text: String, copiedAt: Date = .now, sourceBundleID: String? = nil,
         sourceName: String? = nil, isPinned: Bool = false) {
        self.id = id
        self.text = text
        self.copiedAt = copiedAt
        self.sourceBundleID = sourceBundleID
        self.sourceName = sourceName
        self.isPinned = isPinned
    }

    /// The first two non-empty lines, trimmed: what a slip shows.
    var preview: String {
        let lines = text.split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        return lines.prefix(2).joined(separator: "\n")
    }

    /// A short name for the shelf and VoiceOver: the first line, cut at 48 characters.
    var title: String {
        let line = preview.split(whereSeparator: \.isNewline).first.map(String.init) ?? ""
        return line.count > 48 ? String(line.prefix(47)) + "…" : line
    }
}

// MARK: - Privacy

/// What the clipboard history never keeps. Two independent signals, either one is enough:
///
/// - **Markers on the pasteboard** (nspasteboard.org and the private types password managers and text expanders
///   add): concealed (passwords), transient (restored in a moment), auto-generated (nobody pressed ⌘C).
/// - **The app it came from** is a password manager, whether it says so with `org.nspasteboard.source` or is simply
///   the frontmost app when the copy happened. Covers managers that don't mark their copies.
enum ClipboardPrivacy {
    static let concealedType = "org.nspasteboard.ConcealedType"
    static let transientType = "org.nspasteboard.TransientType"
    static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    /// Its value is the bundle id of the app that wrote the pasteboard.
    static let sourceType = "org.nspasteboard.source"

    /// Types that mean "don't read or keep this" (nspasteboard.org, plus the private markers Maccy and Alfred honour).
    static let privateTypes: Set<String> = [
        concealedType,
        transientType,
        autoGeneratedType,
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
    ]

    /// Password managers, by bundle id (lowercased). Exact ids first, then vendor prefixes, since vendors rename
    /// their apps between major versions (1Password 7 → 8, App Store vs direct builds).
    static let passwordManagerBundleIDs: Set<String> = [
        "com.apple.keychainaccess",
        "com.apple.passwords",
        "com.apple.passwords-app",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword-osx",
        "com.agilebits.onepassword4",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.lastpass",
        "com.lastpass.lastpassmacdesktop",
        "com.dashlane.dashlanephonefinal",
        "in.sinew.enpass-desktop",
        "com.keepersecurity.passwordmanager",
        "me.proton.pass.electron",
        "com.markmcguill.strongbox.mac",
        "com.markmcguill.strongbox",
        "com.github.mstarke.macpass",
        "com.outercorner.secrets",
        "com.nordsec.nordpass",
        "com.roboform.roboform",
    ]

    static let passwordManagerPrefixes: [String] = [
        "com.1password.", "com.agilebits.", "com.bitwarden.", "org.keepassxc.", "com.lastpass.", "com.dashlane.",
        "in.sinew.enpass", "com.keepersecurity.", "me.proton.pass", "com.markmcguill.strongbox", "com.nordsec.nordpass",
    ]

    static func isPasswordManager(_ bundleID: String?) -> Bool {
        guard let id = bundleID?.lowercased(), !id.isEmpty else { return false }
        return passwordManagerBundleIDs.contains(id) || passwordManagerPrefixes.contains { id.hasPrefix($0) }
    }

    static func isPrivate(types: [String]) -> Bool {
        types.contains(where: privateTypes.contains)
    }

    enum Decision: Equatable, Sendable {
        /// Plain text from an ordinary app: read it and keep it.
        case record
        /// Marked private, or copied in a password manager: never read.
        case skipPrivate
        /// Files, images, nothing textual: not for this history.
        case skipNotText
    }

    /// Decides from the types alone (reading them never shows the pasteboard privacy alert) whether the contents
    /// may be read at all.
    static func decide(types: [String], frontmostBundleID: String?) -> Decision {
        if isPrivate(types: types) || isPasswordManager(frontmostBundleID) { return .skipPrivate }
        let fileURL = "public.file-url"
        guard !types.contains(fileURL) else { return .skipNotText }
        let textTypes: Set<String> = ["public.utf8-plain-text", "NSStringPboardType", "public.url"]
        return types.contains(where: textTypes.contains) ? .record : .skipNotText
    }

    /// Longest text kept, in UTF-16 units (≈ 100 KB): a copied log file isn't something you paste back from here,
    /// and fifty of them would weigh on memory.
    static let maxTextLength = 100_000

    /// The text worth keeping, or nil: empty, only whitespace, or too long.
    static func keepable(_ text: String?) -> String? {
        guard let text, text.utf16.count <= maxTextLength,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return text
    }
}

// MARK: - History

/// The slips, newest first. At most `maxItems` in all; pins (at most `maxPinned`) are never pushed out.
struct ClipboardHistory: Codable, Equatable, Sendable {
    static let maxItems = 50
    static let maxPinned = 20

    private(set) var items: [ClipboardItem] = []

    init(items: [ClipboardItem] = []) {
        self.items = items
        trim()
    }

    var pinned: [ClipboardItem] { items.filter(\.isPinned) }
    var recent: [ClipboardItem] { items.filter { !$0.isPinned } }
    /// The order the section shows: pins first, then the rest, each newest first.
    var ordered: [ClipboardItem] { pinned + recent }
    var isEmpty: Bool { items.isEmpty }
    var canPinMore: Bool { pinned.count < Self.maxPinned }

    /// Keeps a copy. The same text copied again moves to the top (keeping its pin) instead of appearing twice.
    @discardableResult
    mutating func record(_ text: String, at date: Date = .now, sourceBundleID: String? = nil,
                         sourceName: String? = nil) -> ClipboardItem {
        var item = ClipboardItem(text: text, copiedAt: date, sourceBundleID: sourceBundleID, sourceName: sourceName)
        if let index = items.firstIndex(where: { $0.text == text }) {
            let existing = items.remove(at: index)
            item.id = existing.id
            item.isPinned = existing.isPinned
            item.sourceBundleID = sourceBundleID ?? existing.sourceBundleID
            item.sourceName = sourceName ?? existing.sourceName
        }
        items.insert(item, at: 0)
        trim()
        return item
    }

    /// Copied back from the section: it becomes the newest.
    mutating func touch(_ id: ClipboardItem.ID, at date: Date = .now) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        var item = items.remove(at: index)
        item.copiedAt = date
        items.insert(item, at: 0)
    }

    @discardableResult
    mutating func remove(_ id: ClipboardItem.ID) -> ClipboardItem? {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return nil }
        return items.remove(at: index)
    }

    /// Pins or unpins. Returns false (and changes nothing) when there are already `maxPinned` pins.
    @discardableResult
    mutating func togglePin(_ id: ClipboardItem.ID) -> Bool {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return false }
        if !items[index].isPinned && !canPinMore { return false }
        items[index].isPinned.toggle()
        trim()
        return true
    }

    /// Clears the history. Pinned slips stay: pinning is how the user says "keep this".
    mutating func clear() {
        items.removeAll { !$0.isPinned }
    }

    /// Slips whose text contains every word of `query` (case- and accent-insensitive), in section order.
    func matching(_ query: String) -> [ClipboardItem] {
        let words = query.split(whereSeparator: \.isWhitespace).map(String.init)
        guard !words.isEmpty else { return ordered }
        return ordered.filter { item in
            words.allSatisfy { item.text.range(of: $0, options: [.caseInsensitive, .diacriticInsensitive]) != nil }
        }
    }

    /// Drops the oldest unpinned slips beyond the cap.
    private mutating func trim() {
        while items.count > Self.maxItems, let index = items.lastIndex(where: { !$0.isPinned }) {
            items.remove(at: index)
        }
    }
}

// MARK: - Keeping it across launches

/// The history on disk, only while the user asked for it (off by default): one JSON file in Application Support,
/// readable by the user alone (0600), with complete file protection, left out of backups. Turning the option off
/// deletes it.
struct ClipboardArchive: Sendable {
    let url: URL

    static let standard = ClipboardArchive(
        url: URL.applicationSupportDirectory.appending(path: "Altillo/Clipboard/history.json")
    )

    func load() -> ClipboardHistory? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(ClipboardHistory.self, from: data)
    }

    func save(_ history: ClipboardHistory) throws {
        let folder = url.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true,
                                                attributes: [.posixPermissions: 0o700])
        let data = try JSONEncoder().encode(history)
        do {
            try data.write(to: url, options: [.atomic, .completeFileProtection])
        } catch {
            // Volumes without data protection refuse the option; the permissions below still keep it private.
            try data.write(to: url, options: [.atomic])
        }
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        var target = url
        try? target.setResourceValues(values)
    }

    func delete() {
        try? FileManager.default.removeItem(at: url)
    }
}
